- type: replace
  path: /instance_groups/name=kapacitor/jobs/name=kapacitor/properties/kapacitor/hipchat/enabled
  value: ((kapacitor_hipchat_enabled)))
- type: replace
  path: /instance_groups/name=kapacitor/jobs/name=kapacitor/properties/kapacitor/hipchat/url
  value: ((kapacitor_hipchat_url)))
- type: replace
  path: /instance_groups/name=kapacitor/jobs/name=kapacitor/properties/kapacitor/hipchat/room
  value: ((kapacitor_hipchat_room)))
- type: replace
  path: /instance_groups/name=kapacitor/jobs/name=kapacitor/properties/kapacitor/hipchat/token
  value: ((kapacitor_hipchat_token)))
- type: replace
  path: /instance_groups/name=kapacitor/jobs/name=kapacitor/properties/kapacitor/hipchat/global
  value: ((kapacitor_hipchat_global)))
- type: replace
  path: /instance_groups/name=kapacitor/jobs/name=kapacitor/properties/kapacitor/hipchat/state-changes-only
  value: ((kapacitor_hipchat_state_changes_only)))
